HmiraVendorHmiraBundle_admin_hmira_vendor_hmira_bundle_Skuska:
    resource: "@HmiraVendorHmiraBundle/Controller/Skuska/"
    type:     admingenerator
    prefix:   /admin/hmira_vendor_hmira_bundle/Skuska

HmiraVendorHmiraBundle_admin_hmira_vendor_hmira_bundle_Frajer:
    resource: "@HmiraVendorHmiraBundle/Controller/Frajer/"
    type:     admingenerator
    prefix:   /admin/hmira_vendor_hmira_bundle/Frajer

hmira_vendor_hmira:
    resource: "@HmiraVendorHmiraBundle/Controller/Frajer/"
    type:     admingenerator
#    resource: "@HmiraVendorHmiraBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
